name: lovebaby

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 5 * * * *

jobs:
  lovebaby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: lovebaby
        run: |
          ./run.sh
