name: lovebaby

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: '*/1 * * * *'

jobs:
  lovebaby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script
        run: ./run.sh
