name: lovebaby

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: '0 */2 * * *'

jobs:
  lovebaby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add execute permission to run.sh
        run: chmod +x ./run.sh
      - name: Run script
        run: ./run.sh
